# Site settings
title: Trusst
email: your-email@domain.com
description: "Trusst, helping communities thrive."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: CA4845
  secondary: 0B525A
  secondary-dark: 171306
  lightBlue: 8BD2DA
  green: A2C13B
  blue: 0B525A
  red: CA4845

# Footer settings
footer:
  copyright: Trusst
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/trusst

# Postal address (add as many lines as necessary)
address:
  - line: 123 Fake St.
  - line: San Francisco, CA 94103

# Credits content
credits: 'Freelance is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
